export const productDiscountList = [
  {
    title: 'apple 買2送1',
    product_id: '1',
    brand_id: '',
    categories_id: '',
    amount: '3',
    discount_amount: '-30',
    start_date: '0911',
    end_date: '0919',
  },
  {
    title: 'banana 20蚊 3個',
    product_id: '2',
    brand_id: '4',
    categories_id: '3',
    amount: '3',
    discount_amount: '-16',
    start_date: '0911',
    end_date: '0919',
  },
  {
    title: '新奇是橙 買3送2',
    product_id: '3',
    brand_id: '4',
    categories_id: '',
    amount: '5',
    discount_amount: '-12',
    start_date: '0911',
    end_date: '0919',
  },
  {
    title: '各類水果 30蚊 4個',
    product_id: '5',
    brand_id: '',
    categories_id: '3',
    amount: '4',
    discount_amount: '-22',
    start_date: '0911',
    end_date: '0919',
  },
];
