export const memberList = [
  {
    id: '1',
    username: 'johnsmith',
    email: 'johnsmith@example.com',
    birthday: '1990-01-10',
    points: 500,
  },
  {
    id: '2',
    username: 'sarahjones',
    email: 'sjones@email.com',
    birthday: '1985-03-15',
    points: 750,
  },
  {
    id: '3',
    username: 'mikedoe',
    email: 'mikedoe12@gmail.com',
    birthday: '1992-11-22',
    points: 250,
  },
  {
    id: '4',
    username: 'emilybrown',
    email: 'emily.brown@example.com',
    birthday: '1994-07-05',
    points: 350,
  },
  {
    id: '5',
    username: 'davidwilson',
    email: 'dwilson@mail.com',
    birthday: '1988-04-30',
    points: 900,
  },
  {
    id: '6',
    username: 'lisasmith',
    email: 'lisa.smith@example.com',
    birthday: '1991-12-12',
    points: 600,
  },
  {
    id: '7',
    username: 'johndoe',
    email: 'johndoe@hotmail.com',
    birthday: '1987-02-18',
    points: 400,
  },
  {
    id: '8',
    username: 'amandajackson',
    email: 'ajackson@email.com',
    birthday: '1995-09-08',
    points: 150,
  },
  {
    id: '9',
    username: 'robertgreen',
    email: 'robert.green@example.com',
    birthday: '1993-05-25',
    points: 800,
  },
  {
    id: '10',
    username: 'michaeltaylor',
    email: 'mtaylor@gmail.com',
    birthday: '1989-10-03',
    points: 700,
  },
];
