export const memberList = [
  {
    id: '1',
    username: 'johnsmith',
    email: 'johnsmith@example.com',
    birthday: '1990-01-10',
    points: 500,
  },
  {
    id: '2',
    username: 'sarahjones',
    email: 'sjones@email.com',
    birthday: '1985-03-15',
    points: 750,
  },
  {
    id: '3',
    username: 'mikedoe',
    email: 'mikedoe12@gmail.com',
    birthday: '1992-11-22',
    points: 250,
  },
  {
    id: '4',
    username: 'emilybrown',
    email: 'emily.brown@example.com',
    birthday: '1994-07-05',
    points: 350,
  },
  {
    id: '5',
    username: 'davidwilson',
    email: 'dwilson@mail.com',
    birthday: '1988-04-30',
    points: 900,
  },
  {
    id: '6',
    username: 'lisasmith',
    email: 'lisa.smith@example.com',
    birthday: '1991-12-12',
    points: 600,
  },
  {
    id: '7',
    username: 'johndoe',
    email: 'johndoe@hotmail.com',
    birthday: '1987-02-18',
    points: 400,
  },
  {
    id: '8',
    username: 'amandajackson',
    email: 'ajackson@email.com',
    birthday: '1995-09-08',
    points: 150,
  },
  {
    id: '9',
    username: 'robertgreen',
    email: 'robert.green@example.com',
    birthday: '1993-05-25',
    points: 800,
  },
  {
    id: '10',
    username: 'michaeltaylor',
    email: 'mtaylor@gmail.com',
    birthday: '1989-10-03',
    points: 700,
  },
];

export const productList = [
  { id: 1, name: 'apple', price: '$30', stock: 999 },
  { id: 2, name: 'banana', price: '$12', stock: 999 },
  { id: 3, name: 'orange', price: '$6', stock: 999 },
  { id: 4, name: 'cherry', price: '$8', stock: 999 },
  { id: 5, name: 'mango', price: '$13', stock: 999 },
  {
    id: 6,
    name: 'Product A',
    stock: 10,
    price: '$19.99',
  },
  {
    id: 7,
    name: 'Product B',
    stock: 5,
    price: '$9.99',
  },
  {
    id: 8,
    name: 'Product C',
    stock: 2,
    price: '$29.99',
  },
  {
    id: 9,
    name: 'Product D',
    stock: 15,
    price: '$14.99',
  },
  {
    id: 10,
    name: 'Product E',
    stock: 8,
    price: '$39.99',
  },
  {
    id: 11,
    name: 'Product F',
    stock: 20,
    price: '$49.99',
  },
  {
    id: 12,
    name: 'Product G',
    stock: 3,
    price: '$24.99',
  },
  {
    id: 13,
    name: 'Product H',
    stock: 12,
    price: '$11.99',
  },
  {
    id: 14,
    name: 'Product I',
    stock: 6,
    price: '$17.99',
  },
  {
    id: 15,
    name: 'Product J',
    stock: 0,
    price: '$9.99',
  },
  {
    id: 16,
    name: 'Product K',
    stock: 4,
    price: '$34.99',
  },
  {
    id: 17,
    name: 'Product L',
    stock: 18,
    price: '$29.99',
  },
  {
    id: 18,
    name: 'Product M',
    stock: 7,
    price: '$12.99',
  },
  {
    id: 19,
    name: 'Product N',
    stock: 9,
    price: '$21.99',
  },
  {
    id: 20,
    name: 'Product O',
    stock: 11,
    price: '$27.99',
  },
  {
    id: 21,
    name: 'Product P',
    stock: 14,
    price: '$14.99',
  },
  {
    id: 22,
    name: 'Product Q',
    stock: 6,
    price: '$19.99',
  },
  {
    id: 23,
    name: 'Product R',
    stock: 3,
    price: '$9.99',
  },
  {
    id: 24,
    name: 'Product S',
    stock: 16,
    price: '$37.99',
  },
  {
    id: 25,
    name: 'Product T',
    stock: 8,
    price: '$23.99',
  },
  {
    id: 26,
    name: 'Product U',
    stock: 5,
    price: '$11.99',
  },
];
