export const productList = [
  {
    brand_id: 7,
    category_id: 15,
    price: 2.99,
    stock: 10,
    name: 'Apple',
  },
  {
    brand_id: 12,
    category_id: 5,
    price: 3.49,
    stock: 15,
    name: 'Cream Cheese',
  },
  {
    brand_id: 19,
    category_id: 9,
    price: 1.99,
    stock: 20,
    name: 'Coke',
  },
  {
    brand_id: 5,
    category_id: 18,
    price: 0.99,
    stock: 8,
    name: 'Cherry',
  },
  {
    brand_id: 24,
    category_id: 7,
    price: 2.49,
    stock: 12,
    name: 'Tuna',
  },
  {
    brand_id: 8,
    category_id: 2,
    price: 4.99,
    stock: 5,
    name: 'Yogurt',
  },
  {
    brand_id: 14,
    category_id: 12,
    price: 3.99,
    stock: 18,
    name: 'Granola',
  },
  {
    brand_id: 21,
    category_id: 3,
    price: 1.49,
    stock: 14,
    name: 'Baguette',
  },
  {
    brand_id: 3,
    category_id: 10,
    price: 2.99,
    stock: 10,
    name: 'Potato Chips',
  },
  {
    brand_id: 26,
    category_id: 6,
    price: 2.49,
    stock: 7,
    name: 'Ketchup',
  },
  {
    brand_id: 10,
    category_id: 17,
    price: 5.99,
    stock: 3,
    name: 'Pasta',
  },
  {
    brand_id: 16,
    category_id: 13,
    price: 4.29,
    stock: 9,
    name: 'Frozen Pizza',
  },
  {
    brand_id: 27,
    category_id: 11,
    price: 2.99,
    stock: 6,
    name: 'Ice Cream',
  },
  {
    brand_id: 9,
    category_id: 8,
    price: 1.99,
    stock: 20,
    name: 'Chocolate Bar',
  },
  {
    brand_id: 17,
    category_id: 16,
    price: 3.49,
    stock: 13,
    name: 'Bread',
  },
  {
    brand_id: 25,
    category_id: 1,
    price: 2.99,
    stock: 8,
    name: 'Lettuce',
  },
  {
    brand_id: 1,
    category_id: 14,
    price: 4.99,
    stock: 5,
    name: 'Salsa',
  },
  {
    brand_id: 23,
    category_id: 10,
    price: 1.99,
    stock: 12,
    name: 'Orange Juice',
  },
  {
    brand_id: 6,
    category_id: 4,
    price: 0.99,
    stock: 11,
    name: 'Banana',
  },
  {
    brand_id: 30,
    category_id: 19,
    price: 2.49,
    stock: 16,
    name: 'Milk',
  },
  {
    brand_id: 13,
    category_id: 7,
    price: 3.99,
    stock: 9,
    name: 'Salmon',
  },
  {
    brand_id: 20,
    category_id: 2,
    price: 1.49,
    stock: 14,
    name: 'Cucumber',
  },
  {
    brand_id: 4,
    category_id: 12,
    price: 2.99,
    stock: 10,
    name: 'Peanut Butter',
  },
  {
    brand_id: 29,
    category_id: 6,
    price: 2.49,
    stock: 7,
    name: 'Mayonnaise',
  },
  {
    brand_id: 11,
    category_id: 17,
    price: 5.99,
    stock: 3,
    name: 'Rice',
  },
  {
    brand_id: 15,
    category_id: 13,
    price: 4.29,
    stock: 9,
    name: 'Frozen Vegetables',
  },
  {
    brand_id: 28,
    category_id: 11,
    price: 2.99,
    stock: 6,
    name: 'Yogurt Drink',
  },
  {
    brand_id: 18,
    category_id: 8,
    price: 1.99,
    stock: 20,
    name: 'Popcorn',
  },
  {
    brand_id: 2,
    category_id: 16,
    price: 3.49,
    stock: 13,
    name: 'Croissant',
  },
  {
    brand_id: 22,
    category_id: 1,
    price: 2.99,
    stock: 8,
    name: 'Tomato',
  },
  {
    brand_id: 12,
    category_id: 5,
    price: 2.99,
    stock: 10,
    name: 'Tuna',
  },
  {
    brand_id: 6,
    category_id: 13,
    price: 3.49,
    stock: 15,
    name: 'Cream Cheese',
  },
  {
    brand_id: 22,
    category_id: 7,
    price: 3.99,
    stock: 18,
    name: 'Granola',
  },
  {
    brand_id: 18,
    category_id: 3,
    price: 2.99,
    stock: 8,
    name: 'Lettuce',
  },
  {
    brand_id: 9,
    category_id: 20,
    price: 3.99,
    stock: 18,
    name: 'Granola',
  },
  {
    brand_id: 3,
    category_id: 17,
    price: 5.99,
    stock: 3,
    name: 'Steak',
  },
  {
    brand_id: 15,
    category_id: 9,
    price: 1.49,
    stock: 14,
    name: 'Baguette',
  },
  {
    brand_id: 7,
    category_id: 14,
    price: 2.99,
    stock: 10,
    name: 'Cookies',
  },
  {
    brand_id: 25,
    category_id: 10,
    price: 3.99,
    stock: 18,
    name: 'Energy Drink',
  },
  {
    brand_id: 2,
    category_id: 6,
    price: 3.49,
    stock: 13,
    name: 'Bread',
  },
  {
    brand_id: 14,
    category_id: 18,
    price: 2.99,
    stock: 10,
    name: 'Apple',
  },
  {
    brand_id: 1,
    category_id: 8,
    price: 4.29,
    stock: 9,
    name: 'Frozen Pizza',
  },
  {
    brand_id: 4,
    category_id: 19,
    price: 2.49,
    stock: 7,
    name: 'Soda',
  },
  {
    brand_id: 10,
    category_id: 16,
    price: 4.99,
    stock: 5,
    name: 'Cheese',
  },
  {
    brand_id: 17,
    category_id: 2,
    price: 2.49,
    stock: 7,
    name: 'Ketchup',
  },
  {
    brand_id: 19,
    category_id: 12,
    price: 1.99,
    stock: 20,
    name: 'Chocolate Bar',
  },
  {
    brand_id: 27,
    category_id: 11,
    price: 1.99,
    stock: 20,
    name: 'Candy',
  },
  {
    brand_id: 11,
    category_id: 15,
    price: 2.49,
    stock: 7,
    name: 'Yogurt',
  },
  {
    brand_id: 8,
    category_id: 4,
    price: 2.99,
    stock: 6,
    name: 'Ice Cream',
  },

  {
    brand_id: 16,
    category_id: 1,
    price: 3.99,
    stock: 12,
    name: 'Coffee',
  },
  {
    brand_id: 29,
    category_id: 10,
    price: 3.99,
    stock: 18,
    name: 'Energy Drink',
  },
  {
    brand_id: 5,
    category_id: 6,
    price: 4.49,
    stock: 8,
    name: 'Bagels',
  },
  {
    brand_id: 21,
    category_id: 16,
    price: 3.99,
    stock: 15,
    name: 'Cheese',
  },
  {
    brand_id: 20,
    category_id: 3,
    price: 1.99,
    stock: 20,
    name: 'Lettuce',
  },
  {
    brand_id: 26,
    category_id: 17,
    price: 5.49,
    stock: 4,
    name: 'Salmon',
  },
  {
    brand_id: 23,
    category_id: 7,
    price: 3.99,
    stock: 18,
    name: 'Granola',
  },
  {
    brand_id: 30,
    category_id: 13,
    price: 2.99,
    stock: 10,
    name: 'Cream Cheese',
  },
  {
    brand_id: 13,
    category_id: 5,
    price: 4.49,
    stock: 8,
    name: 'Tuna',
  },
  {
    brand_id: 24,
    category_id: 20,
    price: 3.99,
    stock: 18,
    name: 'Granola',
  },
  {
    brand_id: 28,
    category_id: 9,
    price: 1.99,
    stock: 17,
    name: 'Baguette',
  },
];
