export const productList = [
  {
    id: 1,
    brand_id: 7,
    category_id: 15,
    price: 2.99,
    stock: 10,
    name: 'Apple',
  },
  {
    id: 2,
    brand_id: 12,
    category_id: 5,
    price: 3.49,
    stock: 15,
    name: 'Cream Cheese',
  },
  {
    id: 3,
    brand_id: 19,
    category_id: 9,
    price: 1.99,
    stock: 20,
    name: 'Coke',
  },
  {
    id: 4,
    brand_id: 5,
    category_id: 18,
    price: 0.99,
    stock: 8,
    name: 'Cherry',
  },
  {
    id: 5,
    brand_id: 24,
    category_id: 7,
    price: 2.49,
    stock: 12,
    name: 'Tuna',
  },
  {
    id: 6,
    brand_id: 8,
    category_id: 2,
    price: 4.99,
    stock: 5,
    name: 'Yogurt',
  },
  {
    id: 7,
    brand_id: 14,
    category_id: 12,
    price: 3.99,
    stock: 18,
    name: 'Granola',
  },
  {
    id: 8,
    brand_id: 21,
    category_id: 3,
    price: 1.49,
    stock: 14,
    name: 'Baguette',
  },
  {
    id: 9,
    brand_id: 3,
    category_id: 10,
    price: 2.99,
    stock: 10,
    name: 'Potato Chips',
  },
  {
    id: 10,
    brand_id: 26,
    category_id: 6,
    price: 2.49,
    stock: 7,
    name: 'Ketchup',
  },
  {
    id: 11,
    brand_id: 10,
    category_id: 17,
    price: 5.99,
    stock: 3,
    name: 'Pasta',
  },
  {
    id: 12,
    brand_id: 16,
    category_id: 13,
    price: 4.29,
    stock: 9,
    name: 'Frozen Pizza',
  },
  {
    id: 13,
    brand_id: 27,
    category_id: 11,
    price: 2.99,
    stock: 6,
    name: 'Ice Cream',
  },
  {
    id: 14,
    brand_id: 9,
    category_id: 8,
    price: 1.99,
    stock: 20,
    name: 'Chocolate Bar',
  },
  {
    id: 15,
    brand_id: 17,
    category_id: 16,
    price: 3.49,
    stock: 13,
    name: 'Bread',
  },
  {
    id: 16,
    brand_id: 25,
    category_id: 1,
    price: 2.99,
    stock: 8,
    name: 'Lettuce',
  },
  {
    id: 17,
    brand_id: 1,
    category_id: 14,
    price: 4.99,
    stock: 5,
    name: 'Salsa',
  },
  {
    id: 18,
    brand_id: 23,
    category_id: 10,
    price: 1.99,
    stock: 12,
    name: 'Orange Juice',
  },
  {
    id: 19,
    brand_id: 6,
    category_id: 4,
    price: 0.99,
    stock: 11,
    name: 'Banana',
  },
  {
    id: 20,
    brand_id: 30,
    category_id: 19,
    price: 2.49,
    stock: 16,
    name: 'Milk',
  },
  {
    id: 21,
    brand_id: 13,
    category_id: 7,
    price: 3.99,
    stock: 9,
    name: 'Salmon',
  },
  {
    id: 22,
    brand_id: 20,
    category_id: 2,
    price: 1.49,
    stock: 14,
    name: 'Cucumber',
  },
  {
    id: 23,
    brand_id: 4,
    category_id: 12,
    price: 2.99,
    stock: 10,
    name: 'Peanut Butter',
  },
  {
    id: 24,
    brand_id: 29,
    category_id: 6,
    price: 2.49,
    stock: 7,
    name: 'Mayonnaise',
  },
  {
    id: 25,
    brand_id: 11,
    category_id: 17,
    price: 5.99,
    stock: 3,
    name: 'Rice',
  },
  {
    id: 26,
    brand_id: 15,
    category_id: 13,
    price: 4.29,
    stock: 9,
    name: 'Frozen Vegetables',
  },
  {
    id: 27,
    brand_id: 28,
    category_id: 11,
    price: 2.99,
    stock: 6,
    name: 'Yogurt Drink',
  },
  {
    id: 28,
    brand_id: 18,
    category_id: 8,
    price: 1.99,
    stock: 20,
    name: 'Popcorn',
  },
  {
    id: 29,
    brand_id: 2,
    category_id: 16,
    price: 3.49,
    stock: 13,
    name: 'Croissant',
  },
  {
    id: 30,
    brand_id: 22,
    category_id: 1,
    price: 2.99,
    stock: 8,
    name: 'Tomato',
  },
  {
    id: 31,
    brand_id: 12,
    category_id: 5,
    price: 2.99,
    stock: 10,
    name: 'Tuna',
  },
  {
    id: 32,
    brand_id: 6,
    category_id: 13,
    price: 3.49,
    stock: 15,
    name: 'Cream Cheese',
  },
  {
    id: 33,
    brand_id: 22,
    category_id: 7,
    price: 3.99,
    stock: 18,
    name: 'Granola',
  },
  {
    id: 34,
    brand_id: 18,
    category_id: 3,
    price: 2.99,
    stock: 8,
    name: 'Lettuce',
  },
  {
    id: 35,
    brand_id: 9,
    category_id: 20,
    price: 3.99,
    stock: 18,
    name: 'Granola',
  },
  {
    id: 36,
    brand_id: 3,
    category_id: 17,
    price: 5.99,
    stock: 3,
    name: 'Steak',
  },
  {
    id: 37,
    brand_id: 15,
    category_id: 9,
    price: 1.49,
    stock: 14,
    name: 'Baguette',
  },
  {
    id: 38,
    brand_id: 7,
    category_id: 14,
    price: 2.99,
    stock: 10,
    name: 'Cookies',
  },
  {
    id: 39,
    brand_id: 25,
    category_id: 10,
    price: 3.99,
    stock: 18,
    name: 'Energy Drink',
  },
  {
    id: 40,
    brand_id: 2,
    category_id: 6,
    price: 3.49,
    stock: 13,
    name: 'Bread',
  },
  {
    id: 41,
    brand_id: 14,
    category_id: 18,
    price: 2.99,
    stock: 10,
    name: 'Apple',
  },
  {
    id: 42,
    brand_id: 1,
    category_id: 8,
    price: 4.29,
    stock: 9,
    name: 'Frozen Pizza',
  },
  {
    id: 43,
    brand_id: 4,
    category_id: 19,
    price: 2.49,
    stock: 7,
    name: 'Soda',
  },
  {
    id: 44,
    brand_id: 10,
    category_id: 16,
    price: 4.99,
    stock: 5,
    name: 'Cheese',
  },
  {
    id: 45,
    brand_id: 17,
    category_id: 2,
    price: 2.49,
    stock: 7,
    name: 'Ketchup',
  },
  {
    id: 46,
    brand_id: 19,
    category_id: 12,
    price: 1.99,
    stock: 20,
    name: 'Chocolate Bar',
  },
  {
    id: 47,
    brand_id: 27,
    category_id: 11,
    price: 1.99,
    stock: 20,
    name: 'Candy',
  },
  {
    id: 48,
    brand_id: 11,
    category_id: 15,
    price: 2.49,
    stock: 7,
    name: 'Yogurt',
  },
  {
    id: 49,
    brand_id: 8,
    category_id: 4,
    price: 2.99,
    stock: 6,
    name: 'Ice Cream',
  },

  {
    id: 50,
    brand_id: 16,
    category_id: 1,
    price: 3.99,
    stock: 12,
    name: 'Coffee',
  },
  {
    id: 51,
    brand_id: 29,
    category_id: 10,
    price: 3.99,
    stock: 18,
    name: 'Energy Drink',
  },
  {
    id: 52,
    brand_id: 5,
    category_id: 6,
    price: 4.49,
    stock: 8,
    name: 'Bagels',
  },
  {
    id: 53,
    brand_id: 21,
    category_id: 16,
    price: 3.99,
    stock: 15,
    name: 'Cheese',
  },
  {
    id: 54,
    brand_id: 20,
    category_id: 3,
    price: 1.99,
    stock: 20,
    name: 'Lettuce',
  },
  {
    id: 55,
    brand_id: 26,
    category_id: 17,
    price: 5.49,
    stock: 4,
    name: 'Salmon',
  },
  {
    id: 56,
    brand_id: 23,
    category_id: 7,
    price: 3.99,
    stock: 18,
    name: 'Granola',
  },
  {
    id: 57,
    brand_id: 30,
    category_id: 13,
    price: 2.99,
    stock: 10,
    name: 'Cream Cheese',
  },
  {
    id: 58,
    brand_id: 13,
    category_id: 5,
    price: 4.49,
    stock: 8,
    name: 'Tuna',
  },
  {
    id: 59,
    brand_id: 24,
    category_id: 20,
    price: 3.99,
    stock: 18,
    name: 'Granola',
  },
  {
    id: 60,
    brand_id: 28,
    category_id: 9,
    price: 1.99,
    stock: 17,
    name: 'Baguette',
  },
];
